_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.3
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
C:
    value: 50
batch_size:
    value: 50
checkpoint:
    value: Data/Player1/checkpoint-test3.pth
decay:
    value: 5000
device:
    value: cpu
epochs:
    value: 20000
gamma:
    value: 0.99
learning_rate:
    value: 0.001
model:
    value: |-
        DQN(
          (linear1): Linear(in_features=34, out_features=128, bias=True)
          (linear2): Linear(in_features=128, out_features=64, bias=True)
          (output): Linear(in_features=64, out_features=1, bias=True)
        )
name:
    value: Backgammon -test3
start_epoch:
    value: 0
